on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

name: Create Release / Upload Assets

jobs:
  linux:
    name: Build for Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Build
        run: cargo build --release

      - name: Install cargo-deb
        run: cargo install cargo-deb
        continue-on-error: true

      - name: Create deb package
        run: cargo deb

      - name: "Move to outputs/ folder"
        run: |
          mkdir outputs
          cp target/release/plz outputs/plz-linux-x86_64
          cp target/debian/*.deb outputs/plz-linux-x86_64.deb

      - name: Upload to temporary storage
        uses: actions/upload-artifact@master
        with:
          name: output-artifact
          path: outputs

  linux-musl:
    name: Musl build for Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install Rust musl toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true
          profile: minimal

      - name: Show version information (Rust, cargo, GCC)
        shell: bash
        run: |
          sudo apt install musl-tools
          gcc --version || true
          rustup -V
          rustup toolchain list
          rustup default
          cargo -V
          rustc -V
          musl-gcc --version || true

      - name: Build
        run: cargo build --release --target=x86_64-unknown-linux-musl

      - name: "Move to outputs/ folder"
        run: |
          mkdir outputs
          cp target/x86_64-unknown-linux-musl/release/plz outputs/plz-linux-musl-x86_64

      - name: Upload to temporary storage
        uses: actions/upload-artifact@master
        with:
          name: output-artifact
          path: outputs

  release:
    name: Release assets
    runs-on: ubuntu-latest
    needs: [linux, linux-musl]

    steps:
      - name: Download from temporary storage
        uses: actions/download-artifact@master
        with:
          name: output-artifact
          path: outputs

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: outputs/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
